import type { ImageFlowConfig } from '../shared';

export const baseConfig: ImageFlowConfig = {
	apiKey: 'k',
	baseUrl: 'https://example.com',
	providerId: 'grsai',
	model: 'nano-banana-2',
	params: {},
	aspectRatio: '3:4',
	imageSize: '1K',
	imageSizeMemory: {},
	concurrency: 1,
	workbenchCols: 4,
	tasksCols: 2,
	favoritesCols: 2,
	workbenchTabCols: 4,
	tasksTabCols: 2,
	favoritesTabCols: 2,
	templateCols: 4,
	modelInjections: {},
	workbenchTemplate: '',
	editModel: 'gpt-image-2',
	editAspectRatio: '16:9',
	editImageSize: '2K',
	editImageSizeMemory: {},
	editConcurrency: 3,
	editParams: {},
	namingModel: 'gemini-3.5-flash',
	autoName: true,
	showThumbActions: true,
	showAudioVideo: true,
	cleanEmptyTasksOnStartup: true,
};
